  # Mode can be 'live' or 'sandbox'
development: &default
  mode: sandbox
  client_id: AdDP6Z0PVwCQ3Zu-qd0cFiBJ_whQ2zNLxNV2jQdhfnUXKCiCv69e-pC1vJXPYaDGTm2ZcPyrrAKT2NZc
  client_secret: EKmDJLzG8nW4tDtJUV8NdN9yJ5we5qvW_QxTSjBzXb4pqZ5nqRcBuYl8hJ2sv8ky6BPCNrP1qxAEPLRO
  # # with Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  # # with CA File
  # ssl_options:
  #   ca_file: config/cacert.pem
  # # Override Endpoint
  # rest_endpoint: https://api.sandbox.paypal.com
test:
  <<: *default
production:
  mode: live
  client_id: CLIENT_ID
  client_secret: CLIENT_SECRET
